version = 0.1
[default.deploy.parameters]
stack_name = "app-vectordb"
resolve_s3 = true
s3_prefix = "app-vectordb"
region = "us-east-1"
profile = "janu-dev"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "InstanceType=\"c5.xlarge\" KeyName=\"MilvusKeyPair\""
image_repositories = []
